# Guardar este archivo como: .github/workflows/verificar.yml
name: Verificación Completa de Estructura

on:
  push:
    branches:
      - main # Se ejecuta automáticamente al hacer push a main

jobs:
  validar-archivos:
    runs-on: ubuntu-latest # Entorno virtual Linux

    steps:
      # Paso 1: Clonar el código del repositorio en el contenedor virtual
      - name: Descargar repositorio
        uses: actions/checkout@v4

     # Paso 2: Verificar existencia del archivo principal (index.html)
      - name: Verificar archivo index.html
        run: test -f index.html

      # Paso 3: Verificar archivo css/style.css
      - name: Verificar archivo css/style.css
        run: test -f css/style.css

      # Paso 4: Verificar archivo js/script.js
      - name: Verificar archivo js/script.js
        run: test -f js/script.js